version: '3.8'

services:
  ct_monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ct_monitor
    restart: unless-stopped
    volumes:
      - ./config.json:/monitor/config.json
      - ./.secret.json:/monitor/.secret.json
      - ./logs:/logs
    environment:
      - PYTHONUNBUFFERED=1